#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  mugara_frontend
        bind *:80
        mode http
        default_backend mugara_backend
backend chukwuonyejustice_backend
        balance roundrobin
        server 5785-web
